### ISSUE TITLE
Incompatible with C2me and VMP

### ISSUE THREAD

**Issue by QPCrummer** [2No2Name/worldthreader#1]
When switching dimensions, after 60s the server crashes to a watchdog error. Now the dimension the player is in seems to run fine, but I assume the other dimension is completely locked up. Here is the logs, but it doesn’t seem to be of any use https://mclo.gs/WRalwD4

Also, I asked Ishland (the dev of these two mods) and he said this: “Yeah i make assumption that the server thread should do all the ticking logic. Task queue for specific world dont really exist except worldgen mainThreadExecutor”. If you want to talk to him directly, here’s their discord https://discord.gg/Kdy8NM5HW4

(Also, you were right when you said C2me is only mentioned when there is an issue 😆)

**Comment by wicivo** [comment]
Hmm, it works for me.

**Comment by wicivo** [comment]
1.19.4

**Comment by wicivo** [comment]
Mod list 
![image](https://github.com/2No2Name/worldthreader/assets/116191734/b4ddbde4-d63d-458e-a83f-94da6ebf5c0f)

**Comment by QPCrummer** [comment]
Did you try going through a nether portal? For me it stalled the server until it finally had a watchdog error. I’ll try again with the latest versions of both to see if I cannot reproduce it.

**Comment by wicivo** [comment]
> 

Yes, I went into the portal

**Comment by wicivo** [comment]
I used to crash too, but it looks like after the update 10.41 or 10.51 now they work
